---
author: "Yichen Wang"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(nlme)
```

```{r Load SBS data}
LCM_metadata_path <- "../data/LCM_normal_kidney_metadata.csv"
kidney_weights_path  <- "../data/SBS96_kidney_signature_weights_table.csv"
blood_weights_path  <- "../data/SBS96_blood_signature_weights_table.csv"
bulk_metadata_path <- "../data/bulk_normal_kidney_metadata.csv"
blood_path <- "../data/SBS96_blood_signature_weights_table.csv"

blood_matrix <- read.table(blood_path, header = TRUE)
LCM_metadata <- read.csv(LCM_metadata_path, header = TRUE, stringsAsFactors = FALSE)
bulk_metadata <- read.csv(bulk_metadata_path, header = TRUE, stringsAsFactors = FALSE)

df <- data.frame(Patient = LCM_metadata$Patient, Sample = LCM_metadata$Sample, Structure = LCM_metadata$Structure, Country = LCM_metadata$Country, Sex = LCM_metadata$Sex, Age = LCM_metadata$Age, Burden= LCM_metadata$Normal_SBS_burden)

df2 <- na.omit(unique(data.frame(Patient = LCM_metadata$Patient, Sample = LCM_metadata$Tumor, Structure = "Tumor", Country = LCM_metadata$Country, Sex = LCM_metadata$Sex, Age = LCM_metadata$Age, Burden= LCM_metadata$Tumor_SBS_burden)))
df2 <- df2[!df2$Sample%in% c('PD47592a'),]

df3 <- unique(data.frame(Patient = LCM_metadata$Patient, Sample = NA, Structure = "Blood", Country = LCM_metadata$Country, Sex = LCM_metadata$Sex, Age = LCM_metadata$Age, Burden=NA))
df3 <- df3[df3$Patient %in% substr(colnames(blood_matrix),1,7),]
col_idx <- match(df3$Patient, substr(colnames(blood_matrix),1,7))
df3$Sample <- colnames(blood_matrix)[col_idx]
df3$Burden <- colSums(blood_matrix[col_idx])

new_rows <- data.frame(
  Patient  = "PD55516",
  Sample   = c("PD55516b_ds0001", "PD55516a", "PD55516c"),
  Structure = c("Bulk cortex", "Tumor", "Blood"),
  Country  = "Japan",
  Sex      = "Male",
  Age      = 62,
  Burden   = c(4749, 8275, 1834)
)
df <- rbind(df,df2,df3,new_rows)
df$Structure[df$Structure=='Distal_tubules'] <- 'Distal tubules'
df$Structure[df$Structure=='Proximal_tubules'] <- 'Proximal tubules'
df$Structure <- as.factor(df$Structure)

# Load kidney weights
kidney_weights_raw <- read.csv(path.expand(kidney_weights_path), check.names = FALSE, stringsAsFactors = FALSE)
kidney_weights_raw$Sample <- sub(" .*", "", kidney_weights_raw$Sample)
kidney_weights_raw <- kidney_weights_raw[kidney_weights_raw$Sample %in% df$Sample, , drop = FALSE]
rownames(kidney_weights_raw) <- kidney_weights_raw$Sample

# Load blood weights
blood_weights_raw <- read.csv(path.expand(blood_weights_path), check.names = FALSE, stringsAsFactors = FALSE)
blood_weights_raw$Sample <- sub(" .*", "", blood_weights_raw$Sample)
blood_weights_raw <- blood_weights_raw[blood_weights_raw$Sample %in% df$Sample, , drop = FALSE]
rownames(blood_weights_raw) <- blood_weights_raw$Sample

# Combine kidney and blood weights, using all columns from both
all_cols <- unique(c(colnames(kidney_weights_raw), colnames(blood_weights_raw)))
weights <- data.frame(matrix(NA, nrow = 0, ncol = length(all_cols)))
colnames(weights) <- all_cols

for (sample in df$Sample) {
  row <- data.frame(matrix(0, nrow = 1, ncol = length(all_cols)))
  colnames(row) <- all_cols
  row$Sample <- sample
  
  if (sample %in% rownames(blood_weights_raw)) {
    for (col in colnames(blood_weights_raw)) {
      row[[col]] <- blood_weights_raw[sample, col]
    }
  } else if (sample %in% rownames(kidney_weights_raw)) {
    for (col in colnames(kidney_weights_raw)) {
      row[[col]] <- kidney_weights_raw[sample, col]
    }
  }
  weights <- rbind(weights, row)
}
rownames(weights) <- weights$Sample

# Ensure numeric signature columns 
sig_cols <- setdiff(colnames(weights), "Sample")
weights[sig_cols] <- lapply(weights[sig_cols], function(x) as.numeric(as.character(x)))

# Zero small contributions
weights[sig_cols] <- lapply(weights[sig_cols], function(x) { x[x < 0.05] <- 0; x })

# Compute Unassigned and clamp negatives to zero
weights$Unassigned <- 1 - rowSums(weights[, sig_cols, drop = FALSE], na.rm = TRUE)
weights[sig_cols] <- lapply(weights[sig_cols], function(x) pmax(x, 0))
weights$Unassigned <- pmax(weights$Unassigned, 0)

df <- df %>%
  mutate(
    SBS1  = weights$SBS1 * Burden,
    SBS5  = weights$SBS5 * Burden,
    # SBS7a = weights$SBS7a * Burden,
    # SBS7d = weights$SBS7d * Burden,
    # SBS8  = weights$SBS8 * Burden,
    # SBS9  = weights$SBS9 * Burden,
    SBS12 = weights$SBS12 * Burden,
    # SBS17a = weights$SBS17a * Burden,
    # SBS17b = weights$SBS17b * Burden,
    SBS18 = weights$SBS18 * Burden,
    # SBS19 = weights$SBS19 * Burden,
    SBS22a = weights$SBS22a * Burden,
    SBS22b = weights$SBS22b * Burden,
    SBS22c = weights$SBS22c * Burden,
    SBS40a = weights$SBS40a * Burden,
    SBS40b = weights$SBS40b * Burden,
    SBS40c = weights$SBS40c * Burden,
    SBSB = weights$SBSB * Burden,
    SBSC = weights$SBSC * Burden,
    # SBSD = weights$SBSD * Burden,
    Others = (weights$SBS21 + weights$SBS44 + weights$SBS2 + weights$SBS13 + weights$SBSD) * Burden,
    SBSblood = weights$SBSblood * Burden,
    Unassigned = weights$Unassigned * Burden
  )


head(df)
write.csv(df, "../../data_S1/Fig4_all_samples.csv", row.names = FALSE)
# SBS40c "#D1D69C"
signature_names <- c(
  "SBS40a","SBS40b","SBS40c","SBS5","SBS22a",
  "SBS22b","SBS22c","SBS12","SBS18","SBS1",
  "SBSblood",
  # "APOBEC","SBSD","MSI",
  "SBSB","SBSC","Others", "Unassigned"
)

cols <- c(
  "#8DD3C7", "#CFECBB", "#F4F3B9", "#BD98A2",  "#1f78b4","#8AB1C9",
   "#759696", "#F5847A", "#D3B387", "#17BEBB", 
    "orange", #"#CECBD0", "purple",
  "#cab2d6","#FCCDE5", "#E5E4E6","#8A8A8A"
)
names(cols) <- signature_names
sig_levels <- signature_names
```

```{r plot PD42887, AA high}
summary_AA_case <-df[df$Patient == 'PD42887'&df$Structure!='Bulk cortex',] %>% 
  group_by(Structure) %>% 
  summarize(SBS1 = mean(SBS1),
            SBS5 = mean(SBS5),
            # SBS12 = mean(SBS12),
            SBS22a = mean(SBS22a),
            SBS22b = mean(SBS22b),
            SBS22c = mean(SBS22c),
            SBS40a = mean(SBS40a),
            SBS40b = mean(SBS40b),
            SBS40c = mean(SBS40c),
            SBSB = mean(SBSB),
            SBSC = mean(SBSC),
            SBSblood = mean(SBSblood),
            Others = mean(Others+SBS18+SBS12),
            Unassigned = mean(Unassigned))

write.csv(summary_AA_case, "../../data_S1/Fig4a_PD42887_signature_summary.csv", row.names = FALSE)

test <- gather(summary_AA_case, E1, E2, -Structure)
test$E1<-factor(test$E1,levels = sig_levels)
test$Structure <-  factor(test$Structure,
  levels = factor(c('Blood','Distal tubules', 'Medulla','Glomeruli', 'Proximal tubules', 'Tumor')))

p_sbs1 <- ggplot(test, aes(x = Structure, y = E2, fill = E1)) +
  geom_bar(stat = "identity",show.legend = TRUE) +scale_fill_manual(values=cols)+ theme_bw()+theme(axis.text.x = element_text(angle = 60, hjust = 1, vjust=1.2),axis.ticks.x = element_blank(), legend.key.size = unit(0.2, "cm"), panel.grid=element_blank(),panel.border=element_blank(),text = element_text(size = 6))+
  labs(x = '', y = 'SBS average burden', fill = "Signatures", title = 'PD42887')

p_sbs1

```

```{r plot PD46868, SBS40b high}
summary_SBS40b_case <-df[df$Patient == 'PD46868'&df$Structure!='Bulk cortex',] %>% 
  group_by(Structure) %>% 
  summarize(SBS1 = mean(SBS1),
            SBS5 = mean(SBS5),
            # SBS12 = mean(SBS12),
            # SBS22a = mean(SBS22a),
            # SBS22b = mean(SBS22b),
            # SBS22c = mean(SBS22c),
            SBS40a = mean(SBS40a),
            SBS40b = mean(SBS40b),
            SBS40c = mean(SBS40c),
            SBSB = mean(SBSB),
            SBSC = mean(SBSC),
            SBSblood = mean(SBSblood),
            Others = mean(Others+SBS18+SBS12+SBS22a+SBS22b+SBS22c),
            Unassigned = mean(Unassigned))

write.csv(summary_SBS40b_case, "../../data_S1/Fig4b_PD46868_signature_summary.csv", row.names = FALSE)

test <- gather(summary_SBS40b_case, E1, E2, -Structure)
test$E1<-factor(test$E1,levels = sig_levels)
test$Structure <-  factor(test$Structure,
  levels = factor(c('Blood','Distal tubules', 'Medulla','Glomeruli', 'Proximal tubules', 'Tumor')))

p_sbs2 <- ggplot(test, aes(x = Structure, y = E2, fill = E1)) +
  geom_bar(stat = "identity",show.legend = TRUE) +scale_fill_manual(values=cols)+ theme_bw()+theme(axis.text.x = element_text(angle = 60, hjust = 1, vjust=1.2),axis.ticks.x = element_blank(),legend.key.size = unit(0.2, "cm"), panel.grid=element_blank(),panel.border=element_blank(),text = element_text(size = 6))+
  labs(x = "", y = 'SBS average burden', fill = "Signatures", title = 'PD46868')

p_sbs2

```


```{r plot PD67546, SBS12 high}
summary_SBS12_case <-df[df$Patient == 'PD67546'&df$Structure!='Bulk cortex',] %>% 
  group_by(Structure) %>% 
  summarize(SBS1 = mean(SBS1),
            SBS5 = mean(SBS5),
            SBS12 = mean(SBS12),
            # SBS22a = mean(SBS22a),
            # SBS22b = mean(SBS22b),
            # SBS22c = mean(SBS22c),
            SBS40a = mean(SBS40a),
            SBS40b = mean(SBS40b),
            SBS40c = mean(SBS40c),
            SBSB = mean(SBSB),
            SBSC = mean(SBSC),
            SBSblood = mean(SBSblood),
            Others = mean(Others+SBS18+SBS22a+SBS22b+SBS22c),
            Unassigned = mean(Unassigned))

write.csv(summary_SBS12_case, "../../data_S1/Fig4c_PD67546_signature_summary.csv", row.names = FALSE)

test <- gather(summary_SBS12_case, E1, E2, -Structure)
test$E1<-factor(test$E1,levels = sig_levels)
test$Structure <-  factor(test$Structure,
  levels = factor(c('Distal tubules', 'Medulla','Glomeruli', 'Proximal tubules', 'Tumor')))

p_sbs3 <- ggplot(test, aes(x = Structure, y = E2, fill = E1)) +
  geom_bar(stat = "identity",show.legend = TRUE) +scale_fill_manual(values=cols)+ theme_bw()+theme(axis.text.x = element_text(angle = 60, hjust = 1, vjust=1.2),axis.ticks.x = element_blank(),legend.key.size = unit(0.2, "cm"), panel.grid=element_blank(),panel.border=element_blank(),text = element_text(size = 6))+
  labs(x = "", y = 'SBS average burden', fill = "Signatures", title = 'PD67546')

p_sbs3

```
```{r plot PD55516, SBS12 high}
summary_SBS12_case <-df[df$Patient == 'PD55516',] %>% 
  group_by(Structure) %>% 
  summarize(SBS1 = mean(SBS1),
            SBS5 = mean(SBS5),
            SBS12 = mean(SBS12),
            # SBS22a = mean(SBS22a),
            # SBS22b = mean(SBS22b),
            # SBS22c = mean(SBS22c),
            SBS40a = mean(SBS40a),
            SBS40b = mean(SBS40b),
            SBS40c = mean(SBS40c),
            SBSB = mean(SBSB),
            SBSC = mean(SBSC),
            SBSblood = mean(SBSblood),
            Others = mean(Others+SBS18+SBS22a+SBS22b+SBS22c),
            Unassigned = mean(Unassigned))

write.csv(summary_SBS12_case, "../../data_S1/Fig4d_PD55516_signature_summary.csv", row.names = FALSE)

test <- gather(summary_SBS12_case, E1, E2, -Structure)
test$E1<-factor(test$E1,levels = sig_levels)
test$Structure <-  factor(test$Structure,
  levels = factor(c('Blood', 'Bulk cortex', 'Tumor')))

p_sbs4 <- ggplot(test, aes(x = Structure, y = E2, fill = E1)) +
  geom_bar(stat = "identity",show.legend = TRUE) +scale_fill_manual(values=cols)+ theme_bw()+theme(axis.text.x = element_text(angle = 60, hjust = 1, vjust=1.2),axis.ticks.x = element_blank(),legend.key.size = unit(0.2, "cm"), panel.grid=element_blank(),panel.border=element_blank(),text = element_text(size = 6))+
  labs(x = "", y = 'SBS average burden', fill = "Signatures", title = 'PD55516')

p_sbs4

```

```{r saving plot}
pdf("../../figure/Fig4/4a.pdf",width = 2.2, height = 2.5)
p_sbs1
dev.off()
pdf("../../figure/Fig4/4b.pdf",width = 2.2, height = 2.5)
p_sbs2
dev.off()
pdf("../../figure/Fig4/4c.pdf",width = 2.2, height = 2.5)
p_sbs3
dev.off()
pdf("../../figure/Fig4/4d.pdf",width = 1.85, height = 2.3)
p_sbs4
dev.off()
```